# Generated by Django 5.2 on 2025-06-24 06:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_system', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tbluser',
            name='email',
            field=models.EmailField(db_index=True, max_length=254, unique=True),
        ),
        migrations.AlterField(
            model_name='tbluser',
            name='mobile_number',
            field=models.CharField(db_index=True, max_length=15, unique=True),
        ),
    ]
