# Generated by Django 5.2 on 2025-08-18 08:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("auth_system", "0001_initial"),
        ("ems", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="tbluser",
            name="branch_id",
            field=models.ForeignKey(
                db_column="branch_id",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="ems.tblbranch",
            ),
        ),
        migrations.AddField(
            model_name="tbluser",
            name="department_id",
            field=models.ForeignKey(
                db_column="department_id",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="ems.tbldepartment",
            ),
        ),
        migrations.AddField(
            model_name="tbluser",
            name="designation_id",
            field=models.ForeignKey(
                db_column="designation_id",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="ems.tbldesignation",
            ),
        ),
        migrations.AddField(
            model_name="tbluser",
            name="role_id",
            field=models.ForeignKey(
                db_column="role_id",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="ems.role",
            ),
        ),
    ]
