# Generated by Django 5.2 on 2025-06-27 08:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_system', '0002_alter_tbluser_email_alter_tbluser_mobile_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loginsession',
            name='login_portal',
            field=models.IntegerField(choices=[(1, 'EMS'), (2, 'CMS'), (3, 'LEAD')], default=1),
        ),
    ]
