# Generated by Django 5.2 on 2025-08-20 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("auth_system", "0002_tbluser_branch_id_tbluser_department_id_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="smslog",
            name="sms_type",
            field=models.IntegerField(
                choices=[
                    (1, "Customer Login OTP"),
                    (2, "FD Login OTP"),
                    (3, "Employee Login OTP"),
                    (4, "Lead Verification OTP"),
                    (5, "Send Link"),
                ]
            ),
        ),
    ]
