# Generated by Django 5.2 on 2025-07-11 07:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auth_system', '0005_alter_apilog_user'),
    ]

    operations = [
        migrations.DeleteModel(
            name='APILog',
        ),
    ]
