# Generated by Django 5.2 on 2025-07-12 05:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auth_system', '0006_delete_apilog'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tbluser',
            old_name='two_setup',
            new_name='two_step',
        ),
    ]
