# Generated by Django 5.2 on 2025-07-14 07:18

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_system', '0007_rename_two_setup_tbluser_two_step'),
    ]

    operations = [
        migrations.AddField(
            model_name='loginsession',
            name='session_id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
    ]
