# Generated by Django 5.2 on 2025-07-30 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_system', '0008_loginsession_session_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='tbluser',
            name='last_activity',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
