# Generated by Django 5.2 on 2025-08-04 07:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_system', '0010_apilog'),
        ('ems', '0020_alter_tblempofficialinformation_reporting_to'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tbluser',
            name='branch_id',
        ),
        migrations.RemoveField(
            model_name='tbluser',
            name='department_id',
        ),
        migrations.RemoveField(
            model_name='tbluser',
            name='designation_id',
        ),
        migrations.RemoveField(
            model_name='tbluser',
            name='role_id',
        ),
        migrations.AddField(
            model_name='tbluser',
            name='branch',
            field=models.ForeignKey(db_column='branch_id', null=True, on_delete=django.db.models.deletion.SET_NULL, to='ems.tblbranch'),
        ),
        migrations.AddField(
            model_name='tbluser',
            name='department',
            field=models.ForeignKey(db_column='department_id', null=True, on_delete=django.db.models.deletion.SET_NULL, to='ems.tbldepartment'),
        ),
        migrations.AddField(
            model_name='tbluser',
            name='designation',
            field=models.ForeignKey(db_column='designation_id', null=True, on_delete=django.db.models.deletion.SET_NULL, to='ems.tbldesignation'),
        ),
        migrations.AddField(
            model_name='tbluser',
            name='role',
            field=models.ForeignKey(db_column='role_id', null=True, on_delete=django.db.models.deletion.SET_NULL, to='ems.role'),
        ),
    ]
