# Generated by Django 5.2 on 2025-08-05 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_system', '0011_remove_tbluser_branch_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loginsession',
            name='login_portal',
            field=models.IntegerField(choices=[(1, 'EMS'), (2, 'CMS'), (3, 'LEAD'), (4, 'DEDUP'), (5, 'CODE_OF_CONDUCT')], default=1),
        ),
    ]
