# Generated by Django 5.2 on 2025-08-06 07:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auth_system', '0012_alter_loginsession_login_portal'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tbluser',
            old_name='branch',
            new_name='branch_id',
        ),
        migrations.RenameField(
            model_name='tbluser',
            old_name='department',
            new_name='department_id',
        ),
        migrations.RenameField(
            model_name='tbluser',
            old_name='designation',
            new_name='designation_id',
        ),
        migrations.RenameField(
            model_name='tbluser',
            old_name='role',
            new_name='role_id',
        ),
    ]
