# Generated by Django 5.2 on 2025-08-11 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_system', '0013_rename_branch_tbluser_branch_id_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmailLogs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.CharField(blank=True, max_length=50, null=True)),
                ('email', models.CharField(max_length=200)),
                ('message', models.TextField()),
                ('email_type', models.IntegerField(choices=[(1, 'Enquiry Verification OTP')])),
                ('request_id', models.CharField(blank=True, max_length=255, null=True)),
                ('status', models.IntegerField(choices=[(1, 'Pending'), (2, 'Delivered'), (3, 'Failed'), (4, 'Verified'), (5, 'Expired'), (6, 'Cancelled')])),
                ('sent_at', models.DateTimeField(auto_now_add=True)),
                ('delivered_at', models.DateTimeField(blank=True, null=True)),
                ('response', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'auth_system_email_log',
            },
        ),
    ]
