# Generated by Django 5.2 on 2025-06-28 06:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lead', '0002_propertydocument'),
    ]

    operations = [
        migrations.CreateModel(
            name='LoanAmountRange',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('loan_amount_from', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('loan_amount_to', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('created_by', models.IntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_by', models.IntegerField(blank=True, default=0, null=True)),
                ('updated_at', models.DateTimeField(blank=True, default=None, null=True)),
                ('deleted_by', models.IntegerField(blank=True, default=0, null=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Loan Amount Range',
                'verbose_name_plural': 'Loan Amount Ranges',
            },
        ),
    ]
