# Generated by Django 5.2 on 2025-06-28 06:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lead', '0003_loanamountrange'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loanamountrange',
            name='loan_amount_from',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='loanamountrange',
            name='loan_amount_to',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
