# Generated by Django 5.2 on 2025-07-30 13:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lead', '0005_apilog'),
    ]

    operations = [
        migrations.DeleteModel(
            name='EnquiryType',
        ),
    ]
