# Generated by Django 5.2 on 2025-08-04 11:07

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('created_by', models.IntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_by', models.IntegerField(blank=True, default=0, null=True)),
                ('updated_at', models.DateTimeField(blank=True, default=None, null=True)),
                ('deleted_by', models.IntegerField(blank=True, default=0, null=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='DepositAgents',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deposit_agents_file_upload', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('created_by', models.IntegerField()),
                ('updated_by', models.IntegerField(blank=True, default=0, null=True)),
                ('updated_at', models.DateTimeField(blank=True, default=None, null=True)),
                ('deleted_by', models.IntegerField(blank=True, default=0, null=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('file_status', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='DepositAgentsData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quarter_code', models.CharField(db_index=True, max_length=50)),
                ('name', models.CharField(db_index=True, max_length=255)),
                ('owner_name', models.CharField(db_index=True, max_length=255)),
                ('from_date', models.DateField(blank=True, null=True)),
                ('to_date', models.DateField(blank=True, null=True)),
                ('adhar_number', models.CharField(db_index=True, max_length=20)),
                ('pan_number', models.CharField(db_index=True, max_length=20)),
                ('mobile_number', models.CharField(db_index=True, max_length=15)),
                ('city', models.CharField(max_length=100)),
                ('address', models.TextField()),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('created_by', models.IntegerField()),
                ('updated_by', models.IntegerField(blank=True, default=0, null=True)),
                ('updated_at', models.DateTimeField(blank=True, default=None, null=True)),
                ('deleted_by', models.IntegerField(blank=True, default=0, null=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Dsa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dsa_file_upload', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('created_by', models.IntegerField()),
                ('updated_by', models.IntegerField(blank=True, default=0, null=True)),
                ('updated_at', models.DateTimeField(blank=True, default=None, null=True)),
                ('deleted_by', models.IntegerField(blank=True, default=0, null=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('file_status', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='DsaData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quarter_code', models.CharField(db_index=True, max_length=50)),
                ('name', models.CharField(db_index=True, max_length=255)),
                ('owner_name', models.CharField(db_index=True, max_length=255)),
                ('from_date', models.DateField(blank=True, null=True)),
                ('to_date', models.DateField(blank=True, null=True)),
                ('adhar_number', models.CharField(db_index=True, max_length=20)),
                ('pan_number', models.CharField(db_index=True, max_length=20)),
                ('mobile_number', models.CharField(db_index=True, max_length=15)),
                ('city', models.CharField(max_length=100)),
                ('address', models.TextField()),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('created_by', models.IntegerField()),
                ('updated_by', models.IntegerField(blank=True, default=0, null=True)),
                ('updated_at', models.DateTimeField(blank=True, default=None, null=True)),
                ('deleted_by', models.IntegerField(blank=True, default=0, null=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Languages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('created_by', models.IntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_by', models.IntegerField(blank=True, default=0, null=True)),
                ('updated_at', models.DateTimeField(blank=True, default=None, null=True)),
                ('deleted_by', models.IntegerField(blank=True, default=0, null=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='QuarterMaster',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quarter', models.CharField(max_length=255, unique=True)),
                ('from_date', models.DateField()),
                ('to_date', models.DateField()),
                ('created_by', models.IntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_by', models.IntegerField(blank=True, default=0, null=True)),
                ('updated_at', models.DateTimeField(blank=True, default=None, null=True)),
                ('deleted_by', models.IntegerField(blank=True, default=0, null=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Ras',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ras_file_upload', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('created_by', models.IntegerField()),
                ('update_by', models.IntegerField(blank=True, default=0, null=True)),
                ('updated_at', models.DateTimeField(blank=True, default=None, null=True)),
                ('deleted_by', models.IntegerField(blank=True, default=0, null=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('file_status', models.IntegerField(default=0)),
                ('output_file', models.CharField(blank=True, default=None, max_length=255, null=True)),
            ],
            options={
                'db_table': 'code_of_conduct_ras',
            },
        ),
        migrations.CreateModel(
            name='RasData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quarter_code', models.CharField(db_index=True, max_length=50)),
                ('name', models.CharField(db_index=True, max_length=255)),
                ('owner_name', models.CharField(db_index=True, max_length=255)),
                ('from_date', models.DateField(blank=True, null=True)),
                ('to_date', models.DateField(blank=True, null=True)),
                ('adhar_number', models.CharField(db_index=True, max_length=20)),
                ('pan_number', models.CharField(db_index=True, max_length=20)),
                ('mobile_number', models.CharField(db_index=True, max_length=15)),
                ('city', models.CharField(max_length=100)),
                ('address', models.TextField()),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('created_by', models.IntegerField()),
                ('updated_by', models.IntegerField(blank=True, default=0, null=True)),
                ('updated_at', models.DateTimeField(blank=True, default=None, null=True)),
                ('deleted_by', models.IntegerField(blank=True, default=0, null=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'code_of_conduct_ras_data',
            },
        ),
        migrations.CreateModel(
            name='Questions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('general', 'General'), ('technical', 'Technical'), ('other', 'Other')], max_length=50)),
                ('is_status', models.BooleanField(default=False)),
                ('questions', models.TextField()),
                ('created_by', models.IntegerField()),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_by', models.IntegerField(blank=True, default=None, null=True)),
                ('updated_at', models.DateTimeField(blank=True, default=None, null=True)),
                ('deleted_by', models.IntegerField(blank=True, default=None, null=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('language', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='code_of_conduct.languages')),
            ],
        ),
    ]
