# Generated by Django 5.2 on 2025-08-19 12:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("code_of_conduct", "0002_apilog"),
    ]

    operations = [
        migrations.AlterField(
            model_name="questions",
            name="type",
            field=models.PositiveSmallIntegerField(
                blank=True,
                choices=[(1, "DSA"), (2, "RSA"), (3, "Deposit Agent")],
                null=True,
            ),
        ),
        migrations.AlterModelTable(
            name="brand",
            table="code_of_conduct_brand",
        ),
        migrations.AlterModelTable(
            name="depositagents",
            table="code_of_conduct_deposit_agents_upload",
        ),
        migrations.AlterModelTable(
            name="depositagentsdata",
            table="code_of_conduct_deposit_agents_data",
        ),
        migrations.AlterModelTable(
            name="dsa",
            table="code_of_conduct_dsa_upload",
        ),
        migrations.AlterModelTable(
            name="dsadata",
            table="code_of_conduct_dsa_data",
        ),
        migrations.AlterModelTable(
            name="languages",
            table="code_of_conduct_languages",
        ),
        migrations.AlterModelTable(
            name="quartermaster",
            table="code_of_conduct_quarter_master",
        ),
        migrations.AlterModelTable(
            name="questions",
            table="code_of_conduct_questions",
        ),
        migrations.CreateModel(
            name="AssignQuarter",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "type",
                    models.PositiveSmallIntegerField(
                        blank=True,
                        choices=[(1, "DSA"), (2, "RSA"), (3, "Deposit Agent")],
                        null=True,
                    ),
                ),
                ("created_by", models.IntegerField()),
                ("created_at", models.DateTimeField()),
                ("updated_by", models.IntegerField(blank=True, null=True)),
                ("updated_at", models.DateTimeField(blank=True, null=True)),
                ("deleted_by", models.IntegerField(blank=True, null=True)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                (
                    "language",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="code_of_conduct.languages",
                    ),
                ),
                (
                    "quarter",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="code_of_conduct.quartermaster",
                    ),
                ),
                (
                    "question",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="code_of_conduct.questions",
                    ),
                ),
            ],
            options={
                "db_table": "code_of_conduct_assign_quarter",
            },
        ),
    ]
