# Generated by Django 5.2 on 2025-08-21 11:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ems", "0001_initial"),
        ("lead", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="leadassignlog",
            name="branch",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="ems.tblbranch",
            ),
        ),
        migrations.AlterField(
            model_name="leadassignlog",
            name="employee",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="ems.tblempbasicprofile",
            ),
        ),
    ]
