# Generated by Django 5.1.6 on 2025-08-02 08:14

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lead', '0002_alter_enquiry_occupation'),
    ]

    operations = [
        migrations.AlterField(
            model_name="enquiry",
            name="occupation",
            field=models.IntegerField(
                choices=[(1, "salaried"), (2, "Self-Employed")],
                default=1,  # ✅ GOOD — must be one of the values in the choices list
            ),
            preserve_default=False,
            
        ),
    ]
