# Generated by Django 5.2.4 on 2025-08-06 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lead', '0003_alter_enquiry_occupation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='enquiry',
            name='occupation',
            field=models.CharField(choices=[(1, 'Salaried'), (2, 'Self-Employed')], max_length=100),
        ),
        migrations.AlterField(
            model_name='enquiryverification',
            name='email_verified',
            field=models.IntegerField(choices=[(0, 'Pending'), (1, 'Verified'), (2, 'Skipped')], default=0),
        ),
        migrations.AlterField(
            model_name='enquiryverification',
            name='mobile_status',
            field=models.IntegerField(choices=[(0, 'Pending'), (1, 'Verified'), (2, 'Skipped')], default=0),
        ),
    ]
