# Generated by Django 5.2 on 2025-08-29 07:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("lead", "0003_rename_selfie1_enquiryselfie_selfie_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="leadlog",
            name="status",
            field=models.CharField(
                choices=[
                    ("DRAFT", "Draft"),
                    ("ASSIGNED", "Assigned"),
                    ("UPDATED", "Updated"),
                    ("CLOSED", "Closed"),
                ],
                default="DRAFT",
                max_length=50,
            ),
        ),
    ]
