# Generated by Django 5.2.4 on 2025-08-07 11:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ems', '0002_alter_role_options_alter_rolepermission_options_and_more'),
        ('lead', '0004_alter_enquiry_occupation_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='enquiry',
            name='assign_to',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='ems.tblempbasicprofile'),
        ),
        migrations.AlterField(
            model_name='enquiry',
            name='is_status',
            field=models.IntegerField(choices=[(0, 'Draft'), (1, 'Submitted'), (2, 'Active'), (3, 'Closed'), (4, 'Reject'), (5, 'Re Open')], default=0),
        ),
        migrations.CreateModel(
            name='LeadLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[(0, 'Draft'), (1, 'Submitted'), (2, 'Active'), (3, 'Closed'), (4, 'Reject'), (5, 'Re Open')], default=0, max_length=50)),
                ('remark', models.TextField(blank=True, null=True)),
                ('followup_pickup_date', models.DateField(blank=True, null=True)),
                ('created_by', models.IntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_by', models.IntegerField(blank=True, default=0, null=True)),
                ('updated_at', models.DateTimeField(blank=True, default=None, null=True)),
                ('deleted_by', models.IntegerField(blank=True, default=0, null=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('enquiry', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='lead.enquiry')),
            ],
            options={
                'db_table': 'lead_logs',
            },
        ),
    ]
