# Generated by Django 5.2 on 2025-08-29 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("lead", "0004_alter_leadlog_status"),
    ]

    operations = [
        migrations.AlterField(
            model_name="leadlog",
            name="status",
            field=models.TextField(
                choices=[
                    ("DRAFT", "Draft"),
                    ("ASSIGNED", "Assigned"),
                    ("UPDATED", "Updated"),
                    ("CLOSED", "Closed"),
                ],
                default="DRAFT",
            ),
        ),
    ]
