# Generated by Django 5.2.4 on 2025-08-11 07:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lead', '0005_enquiry_assign_to_alter_enquiry_is_status_leadlog'),
    ]

    operations = [
        migrations.AlterField(
            model_name='enquiry',
            name='occupation',
            field=models.IntegerField(choices=[(1, 'salaried'), (2, 'Self-Employed')]),
        ),
    ]
