# Generated by Django 5.2 on 2025-09-01 12:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("lead", "0005_alter_leadlog_status"),
    ]

    operations = [
        migrations.RenameField(
            model_name="enquiryverification",
            old_name="email_verified",
            new_name="email_status",
        ),
    ]
