# Generated by Django 5.2 on 2025-08-11 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lead', '0007_leadassignlog'),
    ]

    operations = [
        migrations.AlterField(
            model_name='enquiry',
            name='is_status',
            field=models.IntegerField(choices=[(0, 'Draft'), (1, 'Submitted'), (2, 'Verified')], default=0),
        ),
        migrations.AlterField(
            model_name='leadlog',
            name='status',
            field=models.CharField(choices=[(0, 'Draft'), (1, 'Submitted'), (2, 'Verified')], default=0, max_length=50),
        ),
    ]
