# Generated by Django 5.2 on 2025-09-02 07:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("lead", "0007_enquirytickets"),
    ]

    operations = [
        migrations.RenameField(
            model_name="enquirytickets",
            old_name="attachments",
            new_name="attachment",
        ),
    ]
