# Generated by Django 5.2 on 2025-08-11 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lead', '0008_alter_enquiry_is_status_alter_leadlog_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='enquiry',
            name='occupation',
            field=models.IntegerField(choices=[(1, 'salaried'), (2, 'Self-Employed')], default=1),
        ),
    ]
