# Generated by Django 5.2 on 2025-09-02 09:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("lead", "0008_rename_attachments_enquirytickets_attachment"),
    ]

    operations = [
        migrations.RenameField(
            model_name="enquirytickets",
            old_name="attachment",
            new_name="file",
        ),
    ]
