# Generated by Django 5.2 on 2025-09-02 09:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("lead", "0009_rename_attachment_enquirytickets_file"),
    ]

    operations = [
        migrations.RenameField(
            model_name="enquirytickets",
            old_name="file",
            new_name="attachment",
        ),
    ]
