# Generated by Django 5.2 on 2025-09-08 12:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("lead", "0011_enquiryenduser_alter_enquirytickets_status"),
    ]

    operations = [
        migrations.AddField(
            model_name="enquiryloandetails",
            name="end_user",
            field=models.ForeignKey(
                blank=True,
                default=None,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="lead.enquiryenduser",
            ),
        ),
    ]
