# Generated by Django 5.2 on 2025-09-08 12:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("lead", "0012_enquiryloandetails_end_user"),
    ]

    operations = [
        migrations.AlterField(
            model_name="enquiry",
            name="nature_of_business",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="lead.natureofbusiness",
            ),
        ),
    ]
