# Generated by Django 5.2 on 2025-09-10 06:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("lead", "0013_alter_enquiry_nature_of_business"),
    ]

    operations = [
        migrations.AlterField(
            model_name="enquiryenduser",
            name="title",
            field=models.CharField(max_length=255),
        ),
    ]
