# Generated by Django 5.2 on 2025-09-10 08:17

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("lead", "0014_alter_enquiryenduser_title"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="enquiryselfie",
            name="employee_id",
        ),
        migrations.AddField(
            model_name="enquiryselfie",
            name="employee_code",
            field=models.CharField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
