# Generated by Django 5.2 on 2025-09-10 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("lead", "0015_remove_enquiryselfie_employee_id_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="enquiryimages",
            name="employee_id",
        ),
        migrations.AddField(
            model_name="enquiryimages",
            name="employee_code",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="enquiryselfie",
            name="employee_code",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
