# Generated by Django 5.2 on 2025-09-11 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("lead", "0016_remove_enquiryimages_employee_id_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="enquiry",
            name="is_status",
            field=models.IntegerField(
                choices=[
                    (0, "Draft"),
                    (1, "Active"),
                    (2, "Closed"),
                    (3, "Reject"),
                    (4, "Re Open"),
                ],
                default=0,
            ),
        ),
        migrations.AlterField(
            model_name="enquiryimages",
            name="premises_type",
            field=models.CharField(max_length=100),
        ),
    ]
