# Generated by Django 5.2 on 2025-09-11 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("lead", "0017_alter_enquiry_is_status_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="enquiryimages",
            name="document_sub_types",
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
