# Generated by Django 5.2 on 2025-09-19 08:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("lead", "0019_alter_enquiry_is_steps_alter_enquiry_kyc_document"),
    ]

    operations = [
        migrations.AlterField(
            model_name="enquiry",
            name="kyc_document",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
