# Generated by Django 5.2 on 2025-09-19 08:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("lead", "0020_alter_enquiry_kyc_document"),
    ]

    operations = [
        migrations.AlterField(
            model_name="enquiry",
            name="kyc_document",
            field=models.IntegerField(
                blank=True,
                choices=[
                    (1, "Aadhar"),
                    (2, "Pan Card"),
                    (3, "Voter Id"),
                    (4, "driving License"),
                ],
                null=True,
            ),
        ),
    ]
