# Generated by Django 5.2 on 2025-09-23 07:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("lead", "0021_alter_enquiry_kyc_document"),
    ]

    operations = [
        migrations.AddField(
            model_name="enquiry",
            name="unique_code",
            field=models.CharField(blank=True, max_length=100, null=True, unique=True),
        ),
    ]
