# Generated by Django 5.2 on 2025-09-23 12:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("lead", "0022_enquiry_unique_code"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="enquiry",
            name="unique_code",
        ),
    ]
