# Generated by Django 5.2 on 2025-07-10 10:57

import django.utils.timezone
import ems.models.emp_official_information
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ems', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='role',
            options={'verbose_name': 'Role', 'verbose_name_plural': 'Roles'},
        ),
        migrations.AlterModelOptions(
            name='rolepermission',
            options={'verbose_name': 'Role Permission', 'verbose_name_plural': 'Role Permissions'},
        ),
        migrations.AlterField(
            model_name='role',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='role',
            name='role_code',
            field=models.CharField(max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='rolepermission',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='tblempofficialinformation',
            name='profile_photo',
            field=models.ImageField(blank=True, null=True, upload_to=ems.models.emp_official_information.upload_to_profile_photo),
        ),
        migrations.AlterField(
            model_name='tblempofficialinformation',
            name='signature',
            field=models.ImageField(blank=True, null=True, upload_to=ems.models.emp_official_information.upload_to_signature),
        ),
        migrations.AlterField(
            model_name='userbranches',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='userbranches',
            name='employee_id',
            field=models.IntegerField(unique=True),
        ),
        migrations.AddConstraint(
            model_name='rolepermission',
            constraint=models.UniqueConstraint(fields=('role', 'portal_id', 'menu_id'), name='unique_role_portal_menu'),
        ),
    ]
