# Generated by Django 5.2 on 2025-07-11 07:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ems', '0002_alter_role_options_alter_rolepermission_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userbranches',
            name='employee_id',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
