# Generated by Django 5.2 on 2025-12-20 06:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ems', '0002_alter_tblempaddressdetails_address_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tblbranch',
            name='state_group_code',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='tblempbasicprofile',
            name='whatsapp_mobile_number',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='tblempofficialinformation',
            name='employment_status',
            field=models.IntegerField(blank=True, choices=[(0, 'DEACTIVE'), (1, 'ACTIVE'), (2, 'TERMINATE')], default=1, null=True),
        ),
    ]
