# Generated by Django 5.2 on 2025-07-15 07:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ems', '0005_remove_apilog_response_data'),
    ]

    operations = [
        migrations.AddField(
            model_name='tblbranch',
            name='agrrement_limit',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
