# Generated by Django 5.2 on 2025-07-15 11:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ems', '0006_tblbranch_agrrement_limit'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tblbranch',
            old_name='agrrement_limit',
            new_name='agreement_limit',
        ),
    ]
