# Generated by Django 5.2 on 2025-07-17 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ems', '0007_rename_agrrement_limit_tblbranch_agreement_limit'),
    ]

    operations = [
        migrations.AddField(
            model_name='tblbranch',
            name='range',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
