# Generated by Django 5.2 on 2025-07-18 10:39

import ems.models.dealer
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ems', '0009_dealer_subdealer'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dealer',
            name='images2',
        ),
        migrations.RemoveField(
            model_name='dealer',
            name='images3',
        ),
        migrations.AddField(
            model_name='dealer',
            name='image2',
            field=models.ImageField(blank=True, null=True, upload_to=ems.models.dealer.dealer_upload_path),
        ),
        migrations.AddField(
            model_name='dealer',
            name='image3',
            field=models.ImageField(blank=True, null=True, upload_to=ems.models.dealer.dealer_upload_path),
        ),
        migrations.AlterField(
            model_name='dealer',
            name='code',
            field=models.CharField(max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='dealer',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=ems.models.dealer.dealer_upload_path),
        ),
        migrations.AlterField(
            model_name='subdealer',
            name='code',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
