# Generated by Django 5.2 on 2025-07-18 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ems', '0010_remove_dealer_images2_remove_dealer_images3_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dealer',
            name='branch_id',
            field=models.CharField(max_length=50),
        ),
    ]
