# Generated by Django 5.2 on 2025-07-18 12:22

import ems.models.sub_dealer
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ems', '0011_alter_dealer_branch_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subdealer',
            name='branch_id',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='subdealer',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=ems.models.sub_dealer.subdealer_upload_path),
        ),
        migrations.AlterField(
            model_name='subdealer',
            name='images2',
            field=models.ImageField(blank=True, null=True, upload_to=ems.models.sub_dealer.subdealer_upload_path),
        ),
        migrations.AlterField(
            model_name='subdealer',
            name='images3',
            field=models.ImageField(blank=True, null=True, upload_to=ems.models.sub_dealer.subdealer_upload_path),
        ),
    ]
