# Generated by Django 5.2 on 2025-07-18 12:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ems', '0012_alter_subdealer_branch_id_alter_subdealer_image_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='subdealer',
            old_name='images2',
            new_name='image2',
        ),
        migrations.RenameField(
            model_name='subdealer',
            old_name='images3',
            new_name='image3',
        ),
    ]
