# Generated by Django 5.2 on 2025-07-18 12:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ems', '0013_rename_images2_subdealer_image2_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subdealer',
            name='dealer',
            field=models.ForeignKey(blank=True, db_column='dealer_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='subdealers', to='ems.dealer'),
        ),
        migrations.RenameField(
            model_name='subdealer',
            old_name='dealer',
            new_name='dealer_id',
        ),
    ]
