# Generated by Django 5.2 on 2025-07-30 13:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ems', '0014_alter_subdealer_dealer_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='menu',
            name='portal_id',
        ),
        migrations.RemoveField(
            model_name='role',
            name='portal_id',
        ),
        migrations.RemoveField(
            model_name='rolepermission',
            name='portal_id',
        ),
        migrations.RemoveField(
            model_name='tbldesignation',
            name='department_id',
        ),
        migrations.AddField(
            model_name='menu',
            name='portal',
            field=models.ForeignKey(db_column='portal_id', default=1, on_delete=django.db.models.deletion.PROTECT, related_name='menus', to='ems.portal'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='role',
            name='portal',
            field=models.ForeignKey(db_column='portal_id', default=1, on_delete=django.db.models.deletion.PROTECT, related_name='roles', to='ems.portal'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='rolepermission',
            name='portal',
            field=models.ForeignKey(db_column='portal_id', default=1, on_delete=django.db.models.deletion.PROTECT, related_name='role_permissions', to='ems.portal'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tbldesignation',
            name='department',
            field=models.ForeignKey(db_column='department_id', default=1, on_delete=django.db.models.deletion.PROTECT, related_name='designations', to='ems.tbldepartment'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='tbldesignation',
            name='designation_priority',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='tblempbankdetails',
            name='account_number',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
