# Generated by Django 5.2 on 2025-08-02 06:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ems', '0015_remove_menu_portal_id_remove_role_portal_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tblempnomineedetails',
            name='nominee_address',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='tblempnomineedetails',
            name='nominee_mobile',
            field=models.CharField(blank=True, max_length=15, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='tblempnomineedetails',
            name='nominee_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='tblempnomineedetails',
            name='nominee_relation',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
