# Generated by Django 5.2 on 2025-08-02 07:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ems', '0017_country_state_city'),
    ]

    operations = [
        migrations.AddField(
            model_name='state',
            name='state_code',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
