# Generated by Django 5.2 on 2025-08-04 07:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ems', '0019_alter_tblempofficialinformation_reporting_to'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tblempofficialinformation',
            name='reporting_to',
            field=models.ForeignKey(blank=True, db_column='reporting_to', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reporting_employees', to='ems.tblempbasicprofile'),
        ),
    ]
