# Generated by Django 5.2 on 2025-08-05 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ems', '0020_alter_tblempofficialinformation_reporting_to'),
    ]

    operations = [
        migrations.AddField(
            model_name='tblempofficialinformation',
            name='remarks',
            field=models.TextField(blank=True, null=True),
        ),
    ]
